name: aqua_flow
description: "Aqua Flow Mobile Application"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  get: ^4.7.2
  intl: ^0.18.1
  path_provider: ^2.1.2
  permission_handler: ^12.0.1
  url_launcher: ^6.2.4
  pinput: ^5.0.1
  flutter_svg: ^2.1.0
  another_flushbar: ^1.12.32
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_local_notifications: ^19.4.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/svg/
    - assets/png/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900


# flutter:
#   uses-material-design: true
#   assets:
#     - assets/png/
#     - assets/svg/


flutter_icons:
  android: true
  ios: true
  image_path: "assets/png/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/png/app_icon.png"          